FROM node:20-alpine

WORKDIR /app

# Copy package.json và package-lock.json (nếu có)
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ code
COPY . .

EXPOSE 8082

# Chạy ứng dụng bằng script start
CMD ["npm", "start"]
