const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  READY: "READY",
  DELIVERING: "DELIVERING",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

const PAYMENT_METHOD = {
  CARD: "CARD",
  CASH: "CASH",
  PAYPAL: "PAYPAL",
  WALLET: "WALLET",
};

const RABBITMQ_EXCHANGES = {
  ORDER: "order_exchange",
  PAYMENT: "payment_exchange",
  NOTIFICATION: "notification_exchange",
};

const RABBITMQ_QUEUES = {
  PAYMENT_UPDATES: "order.payment.updates",
  ORDER_CREATED: "order.created",
  ORDER_CONFIRMED: "order.confirmed",
  ORDER_CANCELLED: "order.cancelled",
  ORDER_STATUS: "order.status.updates",
};

const ROUTING_KEYS = {
  ORDER_CREATED: "order.created",
  ORDER_CONFIRMED: "order.confirmed",
  ORDER_CANCELLED: "order.cancelled",
  ORDER_STATUS_UPDATED: "order.status.updated",
  PAYMENT_COMPLETED: "payment.completed",
  PAYMENT_FAILED: "payment.failed",
};

const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  RESTAURANT_CLOSED: "RESTAURANT_CLOSED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  RABBITMQ_EXCHANGES,
  RABBITMQ_QUEUES,
  ROUTING_KEYS,
  ERROR_CODES,
};
